apiVersion: gitlab-v2.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: {{ .Values.providerConfig.name }}
  labels:
    {{- include "provider-gitlab-v2.labels" . | nindent 4 }}
spec:
  credentials:
    source: {{ .Values.providerConfig.credentials.source }}
    secretRef:
      name: {{ .Values.providerConfig.credentials.secretRef.name }}
      namespace: {{ .Values.providerConfig.credentials.secretRef.namespace }}
      key: {{ .Values.providerConfig.credentials.secretRef.key }}
  baseURL: {{ .Values.providerConfig.baseURL }}
  insecure: {{ .Values.providerConfig.insecure }}