apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "provider-gitlab-v2.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  credentials: |
    {
      "token": {{ .Values.secret.token | quote }}
    }